openapi: 3.0.0
info:
  title: Ruggine Chat API
  version: 1.0.0
  description: >
    Questa API consente la gestione di una chat strutturata in gruppi e messaggi privati.
    Gli utenti possono registrarsi, effettuare il login, creare gruppi, invitare altri utenti nei gruppi,
    inviare e ricevere messaggi di gruppo o privati.
      
    L'autenticazione è gestita tramite token JWT (JSON Web Token). Una volta effettuato il login,
    l'utente riceve un token JWT che deve essere incluso nelle richieste successive agli endpoint protetti,
    all'interno dell'header HTTP `Authorization`, usando lo schema `Bearer`.
    
    Il token JWT è firmato dal server utilizzando una password conservata in modo sicuro sul server.
    Questo assicura che il token non possa essere alterato o falsificato da terze parti.
    
    
    I JWT permettono di autenticare l'utente senza dover mantenere uno stato lato server.
    Ogni token contiene le informazioni di identità dell'utente e ha una scadenza. 
    Le richieste agli endpoint protetti devono includere un token valido per poter essere accettate.

tags:
  - name: Auth
    description: Endpoint per autenticazione e registrazione
  - name: Groups
    description: Gestione gruppi
  - name: Group Invites
    description: Inviti per entrare nei gruppi
  - name: Group Messages
    description: Messaggi all’interno dei gruppi
  - name: Private Messages
    description: Messaggi privati tra utenti

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Registra un nuovo utente
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '201':
          description: Utente creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Username già esistente

  /auth/login:
    post:
      tags:
        - Auth
      summary: Login utente
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Login riuscito
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenziali non valide

  /groups:
    post:
      tags:
        - Groups
      summary: Crea un nuovo gruppo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
      responses:
        '201':
          description: Gruppo creato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '401':
          description: Token mancante o non valido
        '402':
          description: Nome del gruppo già in uso
    get:
      tags:
        - Groups
      summary: Lista dei gruppi a cui l’utente appartiene
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista dei gruppi
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        '401':
          description: Token mancante o non valido

  /groups/addUser:
    post:
      tags:
        - Groups
      summary: aggiunge un utente al gruppo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                group_name: 
                  type: string
                
      responses:
        '201':
          description: utente aggiunto correttamente
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Token mancante o non valido

  /groups/removeUser:
    post:
      tags:
        - Groups
      summary: rimuove un utente da un gruppo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                group_name: 
                  type: string
                
      responses:
        '201':
          description: utente aggiunto correttamente
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Token mancante o non valido
        '403':
          description: Utente non fa parte del gruppo
        '404':
          description: Gruppo non trovato

  /groupInvites:
    post:
      tags:
        - Group Invites
      summary: Invia un invito a un utente per entrare nel gruppo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - group_name
                - receiver_username
              properties:
                group_name:
                  type: string
                receiver_username:
                  type: string
                  
      responses:
        '201':
          description: Invito creato
        '401':
          description: Token non valido
        '403':
          description: L'utente che vuole creare l'invito non fa parte del gruppo

    get:
      tags:
        - Group Invites
      summary: Ottieni tutti gli inviti ricevuti dall'utente
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista degli inviti
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: integer
                    group_id:
                      type: integer
        '401':
          description: Token non valido

    delete:
      tags:
        - Group Invites
      summary: Cancella un invito al gruppo
      security:
        - bearerAuth: []
      parameters:
        - name: group_id
          in: query
          required: true
          schema:
            type: integer
        - name: invited_user_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Invito cancellato con successo
        '401':
          description: Token non valido
        '403':
          description: Non autorizzato
        '404':
          description: Invito non trovato

  /groupsMessages:
    get:
      tags:
        - Group Messages
      summary: Ottieni i messaggi di gruppo
      security:
        - bearerAuth: []
      parameters:
        - name: group_name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista dei messaggi del gruppo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupMessage'
        '401':
          description: Token non valido
        '403':
          description: Non autorizzato

    post:
      tags:
        - Group Messages
      summary: Invia un messaggio al gruppo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - group_name
                - text
              properties:
                group_name:
                  type: string
                text:
                  type: string
      responses:
        '201':
          description: Messaggio inviato
        '401':
          description: Token non valido
        '403':
          description: Utente non fa parte del gruppo

  /privateMessages:
    post:
      tags:
        - Private Messages
      summary: Invia un messaggio privato
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - receiver_username
                - text
              properties:
                receiver_username:
                  type: string
                text:
                  type: string
      responses:
        '201':
          description: Messaggio inviato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateMessage'
        '401':
          description: Token non valido
        '404':
          description: Utente non trovato
    get:
      tags:
        - Private Messages
      summary: Ottieni tutti i messaggi privati ricevuti dall’utente
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista dei messaggi privati ricevuti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrivateMessage'
        '401':
          description: Token non valido

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password_hash:
          type: string

    Group:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    UserInGroup:
      type: object
      properties:
        group_id:
          type: integer
        user_id:
          type: integer

    PrivateMessage:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        sender_id:
          type: integer
        receiver_id:
          type: integer
        sent_at:
          type: string
          format: date-time

    GroupMessage:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        sender_id:
          type: integer
        group_rx_id:
          type: integer
        sent_at:
          type: string
          format: date-time