[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15"
actix-web = "4.4"
actix = "0.13.5"
actix-web-actors = "4.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.11.8"
getrandom = "0.2"
libsqlite3-sys = { version = "*", features = ["bundled"] }
jsonwebtoken = "9"
argon2 = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
password-hash = "0.5"
futures = "0.3.31"
chrono = "0.4.41"