// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::prelude::*;
use crate::schema::*;
use chrono::NaiveDateTime;
use diesel::{Identifiable, Queryable};
use serde::{Deserialize, Serialize};

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize, Selectable)]
#[diesel(primary_key(chat_id, user_id))]
#[diesel(table_name = chat_members)]
pub struct ChatMember {
    pub chat_id: i32,
    pub user_id: i32,
    pub joined_at: String,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize, Selectable)]
#[diesel(table_name = chats)]
pub struct Chat {
    pub id: i32,
    pub is_group: bool,
    pub name: Option<String>,//null if private chat
    pub created_by: i32,
    pub created_at: String,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize, Selectable)]
#[diesel(table_name = group_invitation)]
#[diesel(primary_key(group_id, sender_id, receiver_id))]
pub struct GroupInvitation {
    pub group_id: i32,
    pub sender_id: i32,
    pub receiver_id: i32,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize, Selectable)]
#[diesel(table_name = group_message)]
pub struct GroupMessage {
    pub id: Option<i32>,
    pub text: String,
    pub sender_id: i32,
    pub group_rx_id: i32,
    pub sent_at: String,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize, Selectable)]
pub struct Group {
    pub id: Option<i32>,
    pub name: String,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize, Selectable)]
#[diesel(table_name = messages)]
pub struct Message {
    pub id: i32,
    pub chat_id: i32,
    pub sender_id: i32,
    pub content: String,
    pub sent_at: String,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize, Selectable)]
#[diesel(table_name = private_message)]
pub struct PrivateMessage {
    pub id: i32,
    pub text: String,
    pub sender_id: i32,
    pub receiver_id: i32,
    pub sent_at: String,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize, Selectable)]
#[diesel(table_name = user_in_group)]
#[diesel(primary_key(group_id, user_id))]
pub struct UserInGroup {
    pub group_id: i32,
    pub user_id: i32,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize, Selectable)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub password_hash: String,
}
