// Generated by diesel_ext
#![allow(unused)]
#![allow(clippy::all)]
use diesel::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
#[diesel(table_name = crate::schema::group_invitation)]
pub struct GroupInvitation {
    pub id: i32,
    pub group_id: i32,
    pub sender_id: i32,
    pub receiver_id: i32,
}
#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
#[diesel(table_name = crate::schema::group_message)]
pub struct GroupMessage {
    pub id: i32,
    pub text: String,
    pub sender_id: i32,
    pub group_rx_id: i32,
    pub sent_at: String,
}
#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
#[diesel(table_name = crate::schema::groups)]
pub struct Group {
    pub id: Option<i32>,
    pub name: String,
}
#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
#[diesel(table_name = crate::schema::private_message)]
pub struct PrivateMessage {
    pub id: i32,
    pub text: String,
    pub sender_id: i32,
    pub receiver_id: i32,
    pub sent_at: String,
}
#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
#[diesel(table_name = crate::schema::user_in_group)]
#[diesel(primary_key(group_id, user_id))]
pub struct UserInGroup {
    pub group_id: i32,
    pub user_id: i32,
}
#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
#[diesel(table_name = crate::schema::users)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub password_hash: String,
}
